language: csharp
mono: none
dotnet: 3.1.101
os:
  - linux
  - osx
dist: trusty
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:mc3man/trusty-media; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y ffmpeg libgdiplus; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ffmpeg mono-libgdiplus; fi
  - ffmpeg -hwaccels
script:
  - nvm install --lts
  - nvm use --lts
  - node ./.build/travis-ffmpeg-config.js
  - dotnet restore
  - dotnet build ./FFMpegCore/
  - dotnet test ./FFMpegCore.Test/
branches:
  only:
    - master
    - /fix\/.+/
    - /feature\/.+/
