name: NuGet release
on:
  push:
    branches:
      - release
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Prepare .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Build solution
      run: dotnet pack FFMpegCore.sln -c Release

    - name: NuGet login
      id: login
      uses: NuGet/login@8d196754b4036150537f80ac539e15c2f1028841 # v1.2.0
      with:
        user: rosenbjergsoftworks
      
    - name: Publish NuGet package
      run: dotnet nuget push nupkg/*.nupkg --skip-duplicate --source nuget.org --api-key ${{ steps.login.outputs.NUGET_API_KEY }}
